services:
  - type: web
    runtime: python
    name: hr-resume-agent
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: VOYAGE_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ATLAS_CONNECTION_STRING
        sync: false
      - key: PYTHON_VERSION
        value: "3.10.18"
